version: '3.7'
services:
  main:
    build:
      context: .
      dockerfile: development.dockerfile
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - 9229:9229
    entrypoint: ./.docker/entrypoint.sh
    env_file:
      - .env
    networks:
      - default
    depends_on:
      - db
  db:
    image: mysql:5.6.47
    command: --innodb_use_native_aio=0
    expose:
      - 3306
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=app
      - MYSQL_DATABASE=TSTI
    volumes:
      - .docker/db/data:/var/lib/mysql
    networks:
      - default
networks:
  default:
    driver: bridge
